const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const json = value => escape(JSON.stringify(value, null, 2));
export function renderReport(report) {
  const failures = report.results.filter(r => r.status === 'fail').length;
  const uncertain = report.results.filter(r => r.status === 'inconclusive').length;
  const verdict = report.infrastructureError || uncertain ? 'Some checks could not be verified' : failures ? 'Saved state broke its contract' : 'Selected state survived';
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src 'self' data:;"><title>${escape(report.name)} · App Crash Lab</title>
<style>*{box-sizing:border-box}body{margin:0;background:#10131b;color:#e9edf7;font:16px/1.65 system-ui,sans-serif}main{max-width:1050px;margin:auto;padding:44px 24px}.eyebrow{color:#90aaff;letter-spacing:.12em;font-size:12px;font-weight:700}h1{font-size:clamp(30px,5vw,52px);line-height:1.08;letter-spacing:-.04em;margin:16px 0}h2{font-size:23px}p{color:#b8c2d9}a{color:#a0b7ff}article{background:#1a2030;border:1px solid #343f55;border-radius:16px;padding:24px;margin:22px 0}.badge{font-size:13px;letter-spacing:.06em;border-radius:20px;padding:5px 12px;background:#163d33;color:#a9ffd7}.fail{background:#50222e;color:#ffc1cd}.inconclusive{background:#463719;color:#ffe3a3}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}pre{overflow:auto;padding:18px;background:#10131b;border-radius:8px;font-size:13px}table{width:100%;border-collapse:collapse}td,th{text-align:left;vertical-align:top;padding:9px;border-bottom:1px solid #34405a;overflow-wrap:anywhere}code{font-size:13px}small{color:#aab7cd}details{margin-top:16px}img{max-width:100%;border-radius:8px}@media(max-width:650px){.grid{grid-template-columns:1fr}article{padding:16px}main{padding:24px 14px}}</style>
<main><div class="eyebrow">APP CRASH LAB / ${escape(report.pack)}</div><h1>${escape(verdict)}</h1><p>${escape(report.name)}<br>${escape(report.baseURL)} · ${escape(report.createdAt)}</p>
${report.infrastructureError ? `<p>Infrastructure error: ${escape(report.infrastructureError)}</p>` : ''}<p>These results cover your explicit observations and conditions. They do not certify the whole app. <a href="repro.spec.mjs">Standalone Playwright tests</a> · <a href="report.json">JSON</a> · <a href="contract.json">Exact contract</a></p>
${report.results.map(r => `<article><span class="badge ${escape(r.status)}">${escape(r.status.toUpperCase())}</span><h2>${r.check === 'reload' ? 'Save → reload' : 'Rejected update → preserve'}</h2><p>${escape(r.error ?? 'The selected saved values matched the baseline.')} <small>Phase: ${escape(r.phase)}</small></p>
${r.rejection ? `<p>Rejection confirmed: <strong>${r.rejection.confirmed ? 'yes' : 'no'}</strong></p>` : ''}
${r.differences.length ? `<table><thead><tr><th>Value</th><th>Before</th><th>After</th></tr></thead><tbody>${r.differences.map(d => `<tr><td><code>${escape(d.path)}</code><br><small>${escape(d.change)}</small></td><td><code>${json(d.before)}</code></td><td><code>${json(d.after)}</code></td></tr>`).join('')}</tbody></table>` : ''}
<div class="grid"><div><h3>Saved baseline</h3><pre>${json(r.before)}</pre></div><div><h3>After check</h3><pre>${json(r.after)}</pre></div></div>
<p><a href="${escape(r.check)}.trace.zip">Playwright trace</a>${r.screenshot ? ` · <a href="${escape(r.screenshot)}">Final screenshot</a>` : ''}</p>
${r.screenshot ? `<details><summary>See the app</summary><img src="${escape(r.screenshot)}" alt="Final app state for ${escape(r.check)}"></details>` : ''}
<details><summary>Executed steps</summary><pre>${json(r.events)}</pre></details></article>`).join('')}
<footer><small>Runner ${escape(report.version)} · Contract SHA-256 ${escape(report.contractHash)}<br>Reports and traces stay on this machine. Review captured app data before sharing.</small></footer></main></html>`;
}
